name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevent GitHub token conflicts

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --configuration production --output-path docs --base-href /bharatramesh.dev/

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploys to gh-pages (not main)
          folder: docs  # The folder to deploy
          clean: true  # Ensures old files are removed before deploying
          token: ${{ secrets.GH_PAGES_DEPLOY }}
